let User,CustomErrorHandler;_26d‍.x([["default",()=>_26d‍.o]]);_26d‍.w("../../models",[["User",["User"],function(v){User=v}]]);_26d‍.w("../../services/CustomErrorHander",[["default",["CustomErrorHandler"],function(v){CustomErrorHandler=v}]]);


const userController = {
    async me(req, res, next){
        try {
            const user = await User.findOne({_id: req.user._id}).select('-password -updatesAr -__v');
            if(!user) {
                return next(CustomErrorHandler.notFound());
            }
            res.json(user);
        } catch (err) {
            return next(err);
        }
    }
};
_26d‍.d(userController);